name: "my_gene"

# Supply .bed file path (.bim and .fam file need to be in the same directory),
# or .vcf.gz file path (need to be bgzipped or with .tbi index file in the same directory).
variant_data: "/mnt/f/Genome/3K-RG/rawdata/SNP-Seek/Nipponbare_indel.bed"


group:
  group1: "path/to/group1.txt"
  group2: "path/to/group2.txt"


region:
  upstream10k:
    chromosome: chr01
    start: 10000
    end: 20000
  gene_body:
    chromosome: chr01
    start: 20001
    end: 29999
  downstream10k:
    chromosome: chr01
    start: 30000
    end: 40000

region_window: 10000000

